language: node_js
node_js:
- '10'
script:
- yarn setup
- yarn fmt:check
- yarn lint:ts
- yarn build
- yarn test
notifications:
  slack:
    secure: 0pQHi7DbYPI5OA2amfbDltRPCjjoYECzXvPKctrEwq1OuEMMuyvRi0cjFO+a5AGViGaDIYHZ6DO73WrD3dvVJdSKjYwVHldeVS3hn0Dbnni316X/y1RTQ3W6rY/d2dhRsU1nO1vaP3tgNb6e2GSBHzPhykHv0D2FzWeKGU8l/juTdqpV0xv5MktOO5sKQGxbJj/plqAMqrbJJ+GCLGKGXZTjOQgX+QTIVt4zgpeltHFNJbMutJ5p7ScatYDI7ORXybtQjccu0aVuZlHrn8ZoNtVJVfFFAtRPX9SO3p4Wdt95FLzaQcOhfBa+TXXYfQeSdl7jvkW4QjNsKwyUFFQ9ZMJ/aFKdWTtlaJklB59AS4UCbNyic2NtMyVBtfFKhKt73B7jCEc9I18L7ff5jckdRAgXE/QEcSALapL7KEt+obyal/SCq2cGSkvAGH7YqJYetaUKdkzPa2ROUGJ4BHVNsq/jCh8eIRSVClPCl+kbX7N+NpLsUZRqQzErcCmj2xM8Ze6gtHyrYocdnLFFyrLyE4MlWu04m0nrd4ETWOdc44rpJnck+mPenK7ZThzOzlRU8qlbwxh8Y/9A/Ul8gwRADvEB0yX5mzz4JXb6Vb4uLwN4l8QcosaWxtO1u7QftZya2nVScNLFUj8GjVqfwTqqmBuGsFcQyoYmV8o0/VDuUM0=
